# Generated by Django 6.0.3 on 2026-04-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_courserating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='review',
            new_name='reviews',
        ),
    ]
