# Generated by Django 6.0.3 on 2026-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notification_alter_student_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_read_status',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifread_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_text',
            field=models.TextField(verbose_name='Notification Text'),
        ),
    ]
