# Generated by Django 6.0.3 on 2026-05-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
    ]
