# Generated by Django 6.0.3 on 2026-05-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quiz_coursequiz_quizquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='question',
            new_name='questions',
        ),
    ]
