# Generated by Django 6.0.3 on 2026-05-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_question_quizquestions_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='questions',
            new_name='question',
        ),
    ]
